### ISSUE TITLE
Merge into flatdata repository

### ISSUE THREAD

**Issue by VeaaC** [boxdot/flatdata-rs#13]
When would be a good time to do so?

**Comment by boxdot** [comment]
It is not quite back, it was never there. ;)

I guess we can do it whenever we want.

**Comment by gferon** [comment]
@boxdot I believe it would make working on the generator + rust code easier. Once could argue that you worked on your free time then contributed to any OSS project, but it's your choice in the end.

**Comment by boxdot** [comment]
https://github.com/heremaps/flatdata/pull/88
